export type HistoryFactor = {
  label: string;
  samples: number;
  impact: number;
  wins?: number;
  top3?: number;
  winRate?: number;
  top3Rate?: number;
  averageFinish?: number;
};
export type Horse = {
  probabilityKind?: "ranking-share";
  horseId?: string;
  number: number;
  gate?: number;
  name: string;
  score: number;
  odds: number | null;
  popularity: number;
  mark: string;
  style: string;
  verdict: string;
  historyAdjustment?: number;
  historySamples?: number;
  positives: string[];
  cautions: string[];
  weight?: number;
  weightChange?: number;
  pedigree?: string;
  jockey?: string;
  jockeyId?: string;
  trainer?: string;
  age?: number;
  sex?: string;
  weightCarried?: number;
  earlyPosition?: number | null;
  recentPositions?: string[];
  mapPositions?: string[];
  paceAdjustment?: number;
  marketScore?: number;
  reinScore?: number;
  firstProbability?: number;
  secondProbability?: number;
  thirdProbability?: number;
  firstSuitability?: number;
  secondSuitability?: number;
  thirdSuitability?: number;
  marketFirstProbability?: number | null;
  reinMarketFirstProbability?: number | null;
  historyFactors?: HistoryFactor[];
  parameterFactors?: HistoryFactor[];
  roleReasons?: {
    first?: Array<{ feature: string; contribution: number }>;
    second?: Array<{ feature: string; contribution: number }>;
    third?: Array<{ feature: string; contribution: number }>;
  };
};
