"use client";
import {useMemo,useState} from "react";
import {PACE_SCENARIOS,escapeCandidates,scenarioView,scenarioRanking,scenarioLeaders,type PaceScenarioId,type ScenarioHorse} from "@/lib/pace-scenarios";
import {PaceRankComparison} from "@/components/pace-rank-comparison";
import {RaceFormationMap} from "@/components/race-formation-map";
import {RaceReplay} from "@/components/race-replay";
import type {Picks} from "@/lib/marks";
import {roleOrder} from "@/lib/marks";
export function PaceScenarioExplorer({horses,title,course,raceId,pace,league,roleReady,picks,initialScenario="baseline",historicalContext}:{horses:ScenarioHorse[];title:string;course:string;raceId:string;pace:string;league?:"jra"|"nar";roleReady:boolean;picks?:Picks;initialScenario?:PaceScenarioId;historicalContext?:string}){
 const candidates=useMemo(()=>escapeCandidates(horses),[horses]);const [id,setId]=useState<PaceScenarioId>(initialScenario),[leaders,setLeaders]=useState<number[]>(()=>scenarioLeaders(horses,initialScenario,candidates.slice(0,1).map(h=>h.number)));
 const view=useMemo(()=>scenarioView(horses,id,leaders),[horses,id,leaders]),comparisons=useMemo(()=>PACE_SCENARIOS.slice(1).map(s=>scenarioView(horses,s.id,leaders)),[horses,leaders]);
 const ranking=useMemo(()=>scenarioRanking(horses,id,leaders,roleReady),[horses,id,leaders,roleReady]);
 const ranks=useMemo(()=>(["first","second","third"] as const).map(role=>new Map(roleReady?roleOrder(horses,role).map((h,i)=>[h.number,i+1]):[])),[horses,roleReady]);
 if(/ばんえい|障害/.test(course))return <p className="mb-5 rounded-xl border border-slate-700 p-4 text-sm text-slate-300">このレースは平地の展開比較の対象外です。</p>;
 const select=(next:PaceScenarioId)=>{setId(next);setLeaders(scenarioLeaders(horses,next,leaders));};
 return <><section className="mb-5 rounded-2xl border border-violet-300/25 bg-[#111b30] p-4 text-white sm:p-5" data-testid="pace-explorer">
 <h2 className="text-xl font-bold">展開を組み立てる</h2>{historicalContext&&<div className="mt-3 rounded-xl border border-amber-300/30 bg-amber-300/5 p-3"><p className="text-sm font-semibold text-amber-200">参考にした過去開催</p><p className="mt-1 text-sm leading-6">{historicalContext}</p><p className="mt-2 text-xs leading-5 text-slate-300">この年の記録をヒントに、今年の馬で仮定を比較しています。過去のペースを再現した予測ではありません。逃げ馬や展開条件を変えて確認してください。</p></div>}<p className="mt-2 text-sm leading-6 text-slate-300">誰が逃げるか、どんな流れになるか。仮定を切り替えて候補の幅を広げられます。</p>
 <div role="group" aria-label="展開の仮定" className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{PACE_SCENARIOS.map(s=><button type="button" key={s.id} data-scenario={s.id} aria-pressed={id===s.id} onClick={()=>select(s.id)} className={`min-h-12 rounded-xl border p-3 text-left text-sm font-bold ${id===s.id?"border-violet-300 bg-violet-300 text-slate-950":"border-slate-600 bg-slate-900 text-slate-200"}`}>{s.label}</button>)}</div>
 <details className="mt-4 rounded-xl border border-slate-600 p-3" open={id!=="baseline"}><summary className="cursor-pointer text-sm font-semibold">前へ行く馬を選ぶ <span className="text-violet-200">{leaders.length?leaders.map(n=>`${n}番`).join("・"):"未選択"}</span></summary><p className="mt-2 text-xs leading-5 text-slate-400">全頭から選択可能。複数なら競り合う仮定。逃げ候補は脚質「逃げ」または近走の序盤平均3番手以内。記録は最大5走。</p><div role="group" aria-label="前へ行く馬" className="mt-3 flex flex-wrap gap-2">{horses.map(h=><button type="button" key={h.number} aria-pressed={leaders.includes(h.number)} onClick={()=>setLeaders(old=>old.includes(h.number)?old.filter(n=>n!==h.number):[...old,h.number])} className={`min-h-11 max-w-full rounded-lg border px-3 py-2 text-left text-xs ${leaders.includes(h.number)?"border-cyan-300 bg-cyan-300/15 text-cyan-100":"border-slate-600 text-slate-300"}`}>{h.number} {h.name}{candidates.some(c=>c.number===h.number)?"・逃げ候補":""}</button>)}</div><button type="button" onClick={()=>setLeaders(candidates.slice(0,id==="duel"?2:1).map(h=>h.number))} className="mt-2 min-h-10 text-xs text-cyan-200 underline">近走の逃げ候補に戻す</button></details>
 <div aria-live="polite" className="mt-4 rounded-xl bg-black/20 p-4"><p className="font-semibold text-violet-200">{view.scenario.label}：{id==="baseline"?pace:view.scenario.flow}</p><p className="mt-2 text-sm leading-6">{view.scenario.premise}</p><p className="mt-2 text-xs leading-5 text-slate-300">確認ポイント：{view.scenario.watch}</p>{view.warnings.map(w=><p key={w} className="mt-2 text-xs text-amber-200">{w}</p>)}</div>
 <p className="mt-3 text-xs leading-5 text-slate-400">追い風・注意は選んだ条件と脚質・通過順による参考相性です。的中確率・展開の発生確率ではありません。着順適性は元のREIN順位を併記します。</p>
 <PaceRankComparison horses={horses} leaders={leaders} roleReady={roleReady} onSelect={select}/>
 <div className="mt-4 grid gap-3 lg:grid-cols-2">{["追い風","注意"].map(label=><div key={label} className="rounded-xl border border-slate-600 p-3"><p className={`text-sm font-bold ${label==="追い風"?"text-cyan-200":"text-amber-200"}`}>{label==="追い風"?"この条件で見直したい馬":"この条件で確認したい馬"}</p><p className="mt-2 text-sm leading-6">{view.rows.filter(r=>r.fit===label).map(r=>`${r.horse.number} ${r.horse.name}`).join(" / ")||"該当なし"}</p></div>)}</div>
 <details className="mt-4 rounded-xl border border-slate-600 p-3"><summary className="min-h-9 cursor-pointer py-2 text-sm font-semibold">展開相性・通過順の根拠を見る</summary><div data-no-swipe style={{overscrollBehaviorX:"contain",touchAction:"pan-x pan-y pinch-zoom"}} className="mt-4 max-h-[36rem] overflow-auto rounded-xl border border-slate-600"><table className="w-full min-w-[700px] text-left text-xs"><caption className="p-3 text-left text-sm font-bold">全頭の展開相性・データ比較（横にスクロール）</caption><thead className="bg-slate-900"><tr>{["馬・脚質","近走の根拠","選んだ条件","着順適性順位","単騎","控えめ","激化","早め","差し"].map(s=><th key={s} scope="col" className="p-3 whitespace-nowrap">{s}</th>)}</tr></thead><tbody>{view.rows.map(r=><tr key={r.horse.number} className="border-t border-slate-700 align-top"><th scope="row" className="p-3"><span className="block whitespace-nowrap">{r.horse.number} {r.horse.name}</span><span className="mt-1 block font-normal text-slate-400">{r.horse.style} / {r.horse.popularity?`${r.horse.popularity}番人気`:"人気未取得"}</span></th><td className="p-3"><p>通過順 {r.evidence.samples}走 / 序盤平均 {r.evidence.early?.toFixed(1)??"—"}番手</p><p className="mt-1 text-slate-400">先頭通過 {r.evidence.leads}走 / 進出 {r.evidence.advances}走</p><p className="mt-1 break-words text-slate-400">{r.evidence.sequences.map(s=>s.join("-")).join(" / ")||"記録なし"}</p></td><td className="p-3"><p className="mb-1 text-cyan-200">条件候補：{ranking.some(v=>v.horse.number===r.horse.number)?`${ranking.find(v=>v.horse.number===r.horse.number)!.rank}位`:"保留"}</p><span className={r.fit==="追い風"?"text-cyan-200":r.fit==="注意"?"text-amber-200":"text-slate-300"}>{r.fit}</span><p className="mt-1 min-w-40 leading-5 text-slate-400">{r.reason}</p></td><td className="p-3 whitespace-nowrap">{ranks.map((rank,i)=><p key={i}>{i+1}着：{rank.get(r.horse.number)?`${rank.get(r.horse.number)}位`:"保留"}</p>)}</td>{comparisons.map(c=><td key={c.scenario.id} className="p-3 whitespace-nowrap">{c.rows.find(v=>v.horse.number===r.horse.number)?.fit}</td>)}</tr>)}</tbody></table></div></details>
 </section><RaceFormationMap key={id} horses={horses} title={title} course={course} raceId={raceId} pace={id!=="baseline"?view.scenario.flow:pace} league={league} scenario={id!=="baseline"?{label:view.scenario.label,positions:Object.fromEntries(view.rows.map(r=>[r.horse.number,r.positions]))}:undefined}/><section data-testid="replay-scenarios" className="mb-3 rounded-xl border border-violet-300/25 bg-[#111b30] p-4 text-white"><h3 className="font-bold">展開ビューの条件を切り替える</h3><div role="group" aria-label="動画の展開条件" className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{PACE_SCENARIOS.map(s=><button key={s.id} type="button" data-replay-scenario={s.id} aria-pressed={id===s.id} onClick={()=>select(s.id)} className={`min-h-12 rounded-xl border p-3 text-left text-sm ${id===s.id?"border-violet-300 bg-violet-300 font-bold text-slate-950":"border-slate-600 text-slate-200"}`}>{s.label}</button>)}</div><p className="mt-3 text-sm font-semibold">{id==="baseline"?"基本の1着適性順":"この条件での参考候補順"}</p><p className="mt-2 text-xs leading-5 text-slate-400">{id==="baseline"?"元のREIN順位で再生します。":"元の1着適性順位を起点に、追い風は2順位分上げ、注意は2順位分下げて並べ直す参考表示です。単騎の逃げ馬・激化の逃げ馬・差しが届く条件は3順位分で比較。同点は元の順位を優先します。的中精度は未検証で、実際にその着順になる確率ではありません。"}</p><ol className="mt-3 space-y-2">{ranking.slice(0,5).map(row=><li key={row.horse.number} className="rounded-lg bg-black/20 p-3 text-sm"><span className="font-bold text-cyan-200">候補{row.rank}　{row.horse.number} {row.horse.name}</span><span className="ml-2 text-xs text-slate-300">基本{row.baseRank}位 → 条件{row.rank}位</span><p className="mt-1 text-xs text-slate-400">{row.reason}</p></li>)}</ol>{!ranking.length&&<p className="mt-2 text-sm text-amber-200">{roleReady?"前へ行く馬の選択条件を満たすまで候補順は保留します。":"1着適性が全頭そろうまで候補順は保留します。"}</p>}</section><RaceReplay key={`${id}:${leaders.join(",")}`} horses={horses} title={title} course={course} raceId={raceId} pace={id!=="baseline"?view.scenario.flow:pace} league={league} picks={picks} roleReady={roleReady} scenario={id!=="baseline"?{label:view.scenario.label,positions:Object.fromEntries(view.rows.map(r=>[r.horse.number,r.positions])),finish:ranking.map(r=>r.horse.number)}:undefined}/></>;
}
