"use client";
import {useMemo,useState} from "react";
import {PACE_SCENARIOS,escapeCandidates,scenarioView,type PaceScenarioId,type ScenarioHorse} from "@/lib/pace-scenarios";
import {RaceFormationMap} from "@/components/race-formation-map";
import {roleOrder} from "@/lib/marks";
export function PaceScenarioExplorer({horses,title,course,raceId,pace,league,roleReady}:{horses:ScenarioHorse[];title:string;course:string;raceId:string;pace:string;league?:"jra"|"nar";roleReady:boolean}){
 const candidates=useMemo(()=>escapeCandidates(horses),[horses]);const [id,setId]=useState<PaceScenarioId>("baseline"),[leaders,setLeaders]=useState<number[]>(()=>candidates.slice(0,1).map(h=>h.number));
 const view=useMemo(()=>scenarioView(horses,id,leaders),[horses,id,leaders]),comparisons=useMemo(()=>PACE_SCENARIOS.slice(1).map(s=>scenarioView(horses,s.id,leaders)),[horses,leaders]);
 const ranks=useMemo(()=>(["first","second","third"] as const).map(role=>new Map(roleReady?roleOrder(horses,role).map((h,i)=>[h.number,i+1]):[])),[horses,roleReady]);
 if(/ばんえい|障害/.test(course))return <p className="mb-5 rounded-xl border border-slate-700 p-4 text-sm text-slate-300">このレースは平地の展開比較の対象外です。</p>;
 const select=(next:PaceScenarioId)=>{setId(next);if(next==="lone"&&leaders.length!==1)setLeaders((leaders.length?leaders:candidates.map(h=>h.number)).slice(0,1));if(next==="duel"&&leaders.length<2)setLeaders(candidates.slice(0,2).map(h=>h.number));};
 return <><section className="mb-5 rounded-2xl border border-violet-300/25 bg-[#111b30] p-4 text-white sm:p-5" data-testid="pace-explorer">
 <h2 className="text-xl font-bold">展開を組み立てる</h2><p className="mt-2 text-sm leading-6 text-slate-300">誰が逃げるか、どんな流れになるか。仮定を切り替えて候補の幅を広げられます。</p>
 <div role="group" aria-label="展開の仮定" className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{PACE_SCENARIOS.map(s=><button type="button" key={s.id} data-scenario={s.id} aria-pressed={id===s.id} onClick={()=>select(s.id)} className={`min-h-12 rounded-xl border p-3 text-left text-sm font-bold ${id===s.id?"border-violet-300 bg-violet-300 text-slate-950":"border-slate-600 bg-slate-900 text-slate-200"}`}>{s.label}</button>)}</div>
 <details className="mt-4 rounded-xl border border-slate-600 p-3" open={id!=="baseline"}><summary className="cursor-pointer text-sm font-semibold">前へ行く馬を選ぶ <span className="text-violet-200">{leaders.length?leaders.map(n=>`${n}番`).join("・"):"未選択"}</span></summary><p className="mt-2 text-xs leading-5 text-slate-400">全頭から選択可能。複数なら競り合う仮定。逃げ候補は脚質「逃げ」または近走の序盤平均3番手以内。記録は最大5走。</p><div role="group" aria-label="前へ行く馬" className="mt-3 flex flex-wrap gap-2">{horses.map(h=><button type="button" key={h.number} aria-pressed={leaders.includes(h.number)} onClick={()=>setLeaders(old=>old.includes(h.number)?old.filter(n=>n!==h.number):[...old,h.number])} className={`min-h-11 max-w-full rounded-lg border px-3 py-2 text-left text-xs ${leaders.includes(h.number)?"border-cyan-300 bg-cyan-300/15 text-cyan-100":"border-slate-600 text-slate-300"}`}>{h.number} {h.name}{candidates.some(c=>c.number===h.number)?"・逃げ候補":""}</button>)}</div><button type="button" onClick={()=>setLeaders(candidates.slice(0,id==="duel"?2:1).map(h=>h.number))} className="mt-2 min-h-10 text-xs text-cyan-200 underline">近走の逃げ候補に戻す</button></details>
 <div aria-live="polite" className="mt-4 rounded-xl bg-black/20 p-4"><p className="font-semibold text-violet-200">{view.scenario.label}：{id==="baseline"?pace:view.scenario.flow}</p><p className="mt-2 text-sm leading-6">{view.scenario.premise}</p><p className="mt-2 text-xs leading-5 text-slate-300">確認ポイント：{view.scenario.watch}</p>{view.warnings.map(w=><p key={w} className="mt-2 text-xs text-amber-200">{w}</p>)}</div>
 <p className="mt-3 text-xs leading-5 text-slate-400">追い風・注意は選んだ条件と脚質・通過順による参考相性です。的中確率・展開の発生確率ではありません。着順適性は元のREIN順位を併記します。</p>
 <div className="mt-4 grid gap-3 lg:grid-cols-2">{["追い風","注意"].map(label=><div key={label} className="rounded-xl border border-slate-600 p-3"><p className={`text-sm font-bold ${label==="追い風"?"text-cyan-200":"text-amber-200"}`}>{label==="追い風"?"この条件で見直したい馬":"この条件で確認したい馬"}</p><p className="mt-2 text-sm leading-6">{view.rows.filter(r=>r.fit===label).map(r=>`${r.horse.number} ${r.horse.name}`).join(" / ")||"該当なし"}</p></div>)}</div>
 <div className="mt-4 max-h-[36rem] overflow-auto rounded-xl border border-slate-600"><table className="w-full min-w-[700px] text-left text-xs"><caption className="p-3 text-left text-sm font-bold">全頭の展開相性・データ比較（横にスクロール）</caption><thead className="bg-slate-900"><tr>{["馬・脚質","近走の根拠","選んだ条件","着順適性順位","単騎","控えめ","激化","早め","差し"].map(s=><th key={s} scope="col" className="p-3 whitespace-nowrap">{s}</th>)}</tr></thead><tbody>{view.rows.map(r=><tr key={r.horse.number} className="border-t border-slate-700 align-top"><th scope="row" className="p-3"><span className="block whitespace-nowrap">{r.horse.number} {r.horse.name}</span><span className="mt-1 block font-normal text-slate-400">{r.horse.style} / {r.horse.popularity?`${r.horse.popularity}番人気`:"人気未取得"}</span></th><td className="p-3"><p>通過順 {r.evidence.samples}走 / 序盤平均 {r.evidence.early?.toFixed(1)??"—"}番手</p><p className="mt-1 text-slate-400">先頭通過 {r.evidence.leads}走 / 進出 {r.evidence.advances}走</p><p className="mt-1 break-words text-slate-400">{r.evidence.sequences.map(s=>s.join("-")).join(" / ")||"記録なし"}</p></td><td className="p-3"><span className={r.fit==="追い風"?"text-cyan-200":r.fit==="注意"?"text-amber-200":"text-slate-300"}>{r.fit}</span><p className="mt-1 min-w-40 leading-5 text-slate-400">{r.reason}</p></td><td className="p-3 whitespace-nowrap">{ranks.map((rank,i)=><p key={i}>{i+1}着：{rank.get(r.horse.number)?`${rank.get(r.horse.number)}位`:"保留"}</p>)}</td>{comparisons.map(c=><td key={c.scenario.id} className="p-3 whitespace-nowrap">{c.rows.find(v=>v.horse.number===r.horse.number)?.fit}</td>)}</tr>)}</tbody></table></div>
 </section><RaceFormationMap key={id} horses={horses} title={title} course={course} raceId={raceId} pace={id!=="baseline"?view.scenario.flow:pace} league={league} scenario={id!=="baseline"?{label:view.scenario.label,positions:Object.fromEntries(view.rows.map(r=>[r.horse.number,r.positions]))}:undefined}/><p className="mb-3 text-xs leading-5 text-slate-400">下の展開ビューは基本想定と1着適性順の再現です。上の条件比較は隊列マップへ反映されます。</p></>;
}
